// PROJECT  :RTCSQWPlotter
// PURPOSE  :You know that already...
// DEVICE   :Arduino + RTC + Plotter
// AUTHOR   :C. D'Arcy
// DATE     :2019 05 02
// MCU      :328p
// COURSE   :ICS3U
// STATUS   :Working
#include  <Wire.h>
#define RTC_ADDRESS 0x68
#define SQWE 4
volatile uint8_t count = 0;   //must add the 'volatile' modifier to any variable updated by an ISR

void setup() {
  Serial.begin(9600);
  digitalWrite(2, HIGH); //set internal pullup resistor for the incoming 'open drain' square wave
  Wire.begin();
  Wire.beginTransmission(RTC_ADDRESS);
  Wire.write(7);
  Wire.write(1 << SQWE);      //
  Wire.endTransmission();
  attachInterrupt(digitalPinToInterrupt(2), pulse, FALLING);
}

void pulse() {
  count++;                    //record every pulse...
}

void loop() {
  //map a stream of integers generated by counting external interrupts
  //triggered by an RTC square wave to alternating 0s and 1s and
  //present the sequence on the ARduino's Serial Plotter.
  Serial.println(count % 2);
}
